var droppoint=function(){this.getArea=function(){$("#droppoint-area").val('');$("#droppoint-area").autocomplete({source:[]});$.ajax({headers:{'X-CSRF-TOKEN':$("input[name=_token]").val()},async:true,type:'POST',url:'/droppoint/area',data:{city:$("#droppoint-city").val()},complete:function(data){var area=$.parseJSON(data.responseText);var areaArray=$.map(area,function(el){return el});$("#droppoint-area").html('');var cg=new customGeneral();cg.autoComplete(areaArray,"#droppoint-area");$("#droppoint-area").autocomplete("search","");}});};this.getDroppoint=function(){$.ajax({headers:{'X-CSRF-TOKEN':$("input[name=_token]").val()},async:true,type:'POST',url:'/droppoint/getHtml',data:{city:$("#droppoint-city").val(),area:$("#droppoint-area").val()},complete:function(data){var html=data.responseText;$('#droppoint-result').html(html);$('#droppoint-result .carousel-container').effect("bounce",{},3000);}});};}
var customGeneral=function(){this.autoScroll=function(className,offset){if($(className).length!=0){$('html, body').animate({scrollTop:$(className).offset().top+offset},1000);}};this.autoComplete=function(array,id){$(id).autocomplete({source:array,autoFocus:true,scroll:true,minLength:0,change:function(ev,ui){if(!ui.item){if($.inArray($(id).val().toUpperCase(),array)>0){$(id).val($(id).val().toUpperCase());}else{$(id).val('');return false;}}}}).focus(function(){if($(this).val()==''){$(this).autocomplete("search","");}else{$(this).autocomplete("search",$(this).val());}});$(id).keypress(function(e){if(e.which==13){var current_value=$(id).val().toUpperCase();if(current_value!=''){if($.inArray(current_value.toUpperCase(),array)>0){$(id).val(current_value);}else{$(id).val('');return false;}}}});};this.autoCompleteNoDropdown=function(array,id){$(id).autocomplete({source:array,autoFocus:true,scroll:true,minLength:0,change:function(ev,ui){if(!ui.item){var found=false;jQuery.each(array,function(i,v){if($(id).val()==v.toLowerCase()){found=true;$(id).val(v);return false;}});}}});};this.postAutoComplete=function(array,id){var postIdElementName=id+'_id';$(id).autocomplete({source:array,autoFocus:true,select:function(ev,ui){if(ui.item){$(postIdElementName).val(ui.item.id);}},change:function(ev,ui){if(!ui.item){var found=false;jQuery.each(array,function(i,v){if($(id).val().toLowerCase()==v.value.toLowerCase()){found=true;$(id).val(v.value);$(postIdElementName).val(v.id);return false;}});if(!found){$(this).val('');}}}});}}
var deliverForm=function(){this.numericValue='';this.initiateCheckNumeric=function(e){this.numericValue=e.value;};this.checkNumeric=function(e){var maxLength=e.maxLength;if(maxLength>0&&e.value.length>maxLength){e.value=e.value.slice(0,maxLength)}
if(e.value==''){this.numericValue='';}else if($.isNumeric(e.value)){this.numericValue=e.value;}else{e.value=this.numericValue;}
return true;};this.validateMinMax=function(e){var maxValue=e.attr("max");var minValue=e.attr("min");if(maxValue!=''&&parseInt(e.val())>parseInt(maxValue)){return true;}else if(minValue!=''&&parseInt(e.val())<parseInt(minValue)){return true;}
return false;};}
var directoryLoader=function(){var current;var directory=[];var directoryAll=[];var placeholder=[];directoryLoader.init=function(){var dir;$.ajax({async:false,type:'GET',url:'/directory/get',complete:function(data){dir=$.parseJSON(data.responseText);}});directoryLoader.placeholder=dir.placeholder;directoryLoader.directory=dir.nodes;directoryLoader.directoryAll=dir.breakdown;directoryLoader.current=new Array();};directoryLoader.init();this.load=function(id,placeholder){var input=placeholder.split(", ");if(input.length==3){directoryLoader.current[id]={'kecamatan':placeholder,'city':input[1],'province':input[2],'finalResult':placeholder};directoryLoader.loadData('kecamatan',id);var option=$('<option></option>').attr("value",placeholder).text(input[0]);$(id).append(option);$(id).val(placeholder);}else{directoryLoader.current[id]={};directoryLoader.loadData('province',id);$(id).val("");}
$(id).on("change",function(e){var selected=$(this).val();var currentSelection=$(this).attr('data-info');if(selected.split(", ").length==3){var split=selected.split(", ");directoryLoader.current[id]={'kecamatan':selected,'city':split[1],'province':split[2],'finalResult':selected};currentSelection='kecamatan';directoryLoader.loadData('kecamatan',id);var option=$('<option></option>').attr("value",selected).text(split[0]);$(id).append(option);$(id).val(selected);}
if(currentSelection=='province'){$(id).select2("destroy").empty();directoryLoader.current[id].province=selected;directoryLoader.loadData('city',id);$(id).val("").select2('open');}else if(currentSelection=='city'){$(id).select2("destroy").empty();if(selected=='back-province'){directoryLoader.loadData('province',id);}else{directoryLoader.current[id].city=selected;directoryLoader.loadData('kecamatan',id);}
$(id).val("").select2('open');}else if(currentSelection=='kecamatan'){if(selected=='back-city'){$(id).select2("destroy").empty();directoryLoader.loadData('city',id);$(id).val("").select2('open');}else{var selectedKecamatan=$(id+' option:selected').text();if(directoryLoader.directory[directoryLoader.current[id].province][directoryLoader.current[id].city][selectedKecamatan]){directoryLoader.current[id].finalResult=selectedKecamatan+', '+directoryLoader.current[id].city+', '+directoryLoader.current[id].province;}}}});};directoryLoader.loadData=function(type,id){$(id).attr('data-info',type);var indicator=new Object();var options=new Array();if(type=='province'){options=directoryLoader.directory;indicator.moduleKey='provinces';indicator.type=type;indicator.text='';indicator.placeholder=directoryLoader.placeholder.province;}else if(type=='city'){options=directoryLoader.directory[directoryLoader.current[id].province];indicator.moduleKey='cityof'+directoryLoader.current[id].province.toLowerCase().replace(' ','');indicator.type=type;indicator.text=directoryLoader.current[id].province;indicator.placeholder=directoryLoader.placeholder.city;}else if(type=='kecamatan'){var kecamatan=directoryLoader.directory[directoryLoader.current[id].province][directoryLoader.current[id].city];if(Object.keys(kecamatan).length>0){var i=0;for(var key in kecamatan){options[key+', '+directoryLoader.current[id].city+', '+directoryLoader.current[id].province]=key;i++;}}
indicator.moduleKey='kecamatanof'+directoryLoader.current[id].city.toLowerCase().replace(' ','');indicator.type=type;indicator.text=directoryLoader.current[id].city;indicator.placeholder=directoryLoader.placeholder.district;}
if(options!=undefined){if(Object.keys(options).length>0){var data=new Array();var i=0;for(var key in options){if(type=='kecamatan'){var eachData={'id':key,'text':options[key]};data.push(eachData);}else{var eachData={'id':key,'text':key};data.push(eachData);}
i++}}
directoryLoader.rebind(data,id,indicator);}};directoryLoader.initializeDataAdapter=function(data,moduleName,indicator){$.fn.select2.amd.define(moduleName,['select2/data/array','select2/utils'],function(ArrayAdapter,Utils){function CustomDataAdapter($element,options){CustomDataAdapter.__super__.constructor.call(this,$element,options);}
Utils.Extend(CustomDataAdapter,ArrayAdapter);CustomDataAdapter.prototype.query=function(params,callback){var datax={results:[]};var pageSize=20;if(!("page"in params)){params.page=1;}
var results=[];var i=0;var objTemp=new Object();objTemp.id='placeholder';objTemp.text=indicator.placeholder;objTemp.disabled=true;results[i]=objTemp;i++;if(indicator.type!='province'){var objTemp=new Object();objTemp.text='< '+indicator.text;results[i++]=objTemp;if(indicator.type=='city'){objTemp.id='back-province';}else if(indicator.type=='kecamatan'){objTemp.id='back-city';}
i++;}
if(params.term){if(params.term.length>0){data.filter(function(obj){var searchRegex='.*'+params.term.toUpperCase()+'.*';if(obj.text.match(searchRegex)){results[i]=obj;i++;}});}}else{results=results.concat(data);}
datax.results=results.slice((params.page-1)*pageSize,params.page*pageSize);datax.pagination={};datax.pagination.more=params.page*pageSize<data.length;callback(datax);};return CustomDataAdapter;});};directoryLoader.rebind=function(data,id,indicator){var allData=data.concat(directoryLoader.directoryAll);var moduleName='select2/data/directoryfor'+indicator.moduleKey;directoryLoader.initializeDataAdapter(allData,moduleName,indicator);var customAdapter=$.fn.select2.amd.require(moduleName);$(id).select2({ajax:{},dataAdapter:customAdapter,placeholder:indicator.placeholder,templateSelection:function template(data){if(data.id===''){return indicator.placeholder;}else if(directoryLoader.current[id].finalResult!=undefined||directoryLoader.current[id].finalResult!=''){return directoryLoader.current[id].finalResult;}else{return data.text;}}});};}